<?php

namespace ClimaClass\ApplicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository {

    public function findMyConversation($user) {
        return $this->getEntityManager()
                    ->createQuery("SELECT c
                    FROM ClimaClassApplicationBundle:Conversation c
                    WHERE c.userCreator = :user OR c.userRecipient = :user")
                        ->setParameter("user", $user)
                        ->getResult();
    }

}
