<?php

namespace ClimaClass\ApplicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository {

    public function findReportForHomepage() {
        $date = date('Y-m-d H:i:s');
        $date_month_prev = date("Y-m-d H:i:s", strtotime($date . "- 1 months"));
        return $this->getEntityManager()
                        ->createQuery("SELECT r
                    FROM ClimaClassApplicationBundle:Report r
                    WHERE r.postDate BETWEEN :nowmonthprev AND :now
                    ORDER BY r.postDate DESC")
                        ->setParameter("now", $date)
                        ->setParameter("nowmonthprev", $date_month_prev)
                        ->getResult();
    }

    public function findReportForCharts($user) {
        $date = date('Y-m-d');
        $date_year_prev = date("Y-m-01", strtotime($date . "- 1 years + 1month "));
        return $this->getEntityManager()
                        ->createQuery("SELECT r
                    FROM ClimaClassApplicationBundle:Report r
                    WHERE r.postDate BETWEEN :nowyearprev AND :now AND r.user = :user")
                        ->setParameter("now", $date)
                        ->setParameter("nowyearprev", $date_year_prev)
                        ->setParameter("user", $user)
                        ->getResult();
    }

}
