<?php

namespace ClimaClass\ApplicationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    public function findReportForHomepage(){
        $date = date('Y-m-d H:i:s');
        $date_month_prev = date("Y-m-d H:i:s",strtotime($date."- 1 months"));
        return $this->getEntityManager()
        ->createQuery("SELECT r
                    FROM ClimaClassApplicationBundle:Report r
                    WHERE r.postDate BETWEEN :nowmonthprev AND :now")
        ->setParameter("now", $date)
        ->setParameter("nowmonthprev", $date_month_prev)
        ->getResult();
    }
}
