# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    climaclass.twig_extension.class: ClimaClass\ApplicationBundle\Twig\TwigExtension

services:
    climaclass.twig_extension:
        class: %climaclass.twig_extension.class%
        tags:
            - { name: twig.extension }